export enum EServiceTabs {
  DASHBOARD = 'dashboard',
  /** 负载量 */
  PAYLOAD = 'payload',
  /** 性能 */
  PERFORMANCE = 'performance',
  /** 响应时间配置 */
  PERFORMANCESETTING = 'performanceSetting',
  /** 基线 */
  BASELINE = 'baseline',
  /** TCP指标 */
  TCPSTATS = 'tcpStats',
  /** 业务路径 */
  TOPOLOGY = 'topology',
  /** 告警消息 */
  ALERT = 'alert',
  /** 应用层协议分析 */
  METADATA = 'metadata',
  /** 流量分析 */
  FLOW = 'flow',
  /** 重传分析 */
  RETRANSMISSION = 'retransmission',
  /** 建连分析 */
  CONNECTION = 'connection',
  /** 会话详单 */
  FLOWRECORD = 'flowRecord',
  /** 数据包 */
  PACKET = 'packet',
  /** 在线分析 */
  PACKETANALYSIS = 'packetanalysis',
}
