import { bytesToSize } from "@/utils/utils";

export const SegmentsCol = [
  {
    title: '网络ID',
    dataIndex: 'networkId',
    key: '网络ID',
    // sorter: true,
    align: 'center',
  },
  // {
  //   title: '网络组ID',
  //   dataIndex: 'networkGroupId',
  //   key: '网络组ID',
  //   // sorter: true,
  //   align: 'center',
  // },
  {
    title: '类型',
    dataIndex: 'networkType',
    key: '类型',
    align: 'center',
  },
  {
    title: '总字节数',
    dataIndex: 'totalBytes',
    key: '总字节数',
    sortOrder: 'descend',
    sorter: true,
    ellipsis: true,
    align: 'center',
    render: (text: any) => {
      return bytesToSize(text);
    },
  },
  {
    title: '总数据包',
    dataIndex: 'totalPackets',
    key: '总数据包',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '新建会话数',
    dataIndex: 'establishedSessions',
    key: '新建会话数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP客户端网络总时延',
    dataIndex: 'tcpClientNetworkLatency',
    key: 'TCP客户端网络总时延',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP客户端网络时延统计次数',
    dataIndex: 'tcpClientNetworkLatencyCounts',
    key: 'TCP客户端网络时延统计次数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP服务端网络总时延',
    dataIndex: 'tcpServerNetworkLatency',
    key: 'TCP服务端网络总时延',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP服务端网络时延统计次数',
    dataIndex: 'tcpServerNetworkLatencyCounts',
    key: 'TCP服务端网络时延统计次数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '服务端响应总时延',
    dataIndex: 'serverResponseLatency',
    key: '服务端响应总时延',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '服务端响应时延统计次数',
    dataIndex: 'serverResponseLatencyCounts',
    key: '服务端响应时延统计次数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },

  {
    title: '接收数据包数',
    dataIndex: 'downstreamPackets',
    key: '接收数据包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '发送数据包数',
    dataIndex: 'upstreamPackets',
    key: '发送数据包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP客户端总包数',
    dataIndex: 'tcpClientPackets',
    key: 'TCP客户端总包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP客户端重传包数',
    dataIndex: 'tcpClientRetransmissionPackets',
    key: 'TCP客户端重传包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP服务端总包数',
    dataIndex: 'tcpServerPackets',
    key: 'TCP服务端总包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP服务端重传包数',
    dataIndex: 'tcpServerRetransmissionPackets',
    key: 'TCP服务端重传包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '客户端零窗口包数',
    dataIndex: 'tcpClientZeroWindowPackets',
    key: '客户端零窗口包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },  
  {
    title: '服务端零窗口包数',
    dataIndex: 'tcpServerZeroWindowPackets',
    key: '服务端零窗口包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP建连成功数',
    dataIndex: 'tcpEstablishedSuccessCounts',
    key: 'TCP建连成功数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP建连失败数',
    dataIndex: 'tcpEstablishedFailCounts',
    key: 'TCP建连失败数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  // {
  //   title: '操作',
  //   dataIndex: 'operate',
  //   key: '操作',
  //   sorter: false,
  //   ellipsis: false,
  //   align: 'center',
  // },
];
