CREATE TABLE IF NOT EXISTS fpc.t_fpc_metric_application_data_record
( 
`timestamp` DateTime64(3, 'UTC') COMMENT '时间',
`network_id` String COMMENT '网络ID',
`service_id` String COMMENT '业务ID',
`application_id` UInt16 COMMENT '应用ID',
`category_id` UInt16 COMMENT '应用分类ID',
`subcategory_id` UInt16 COMMENT '应用子分类ID',
`type` UInt8 COMMENT '应用类别(0:分类,1:子分类,2:应用)',
`total_bytes` UInt64 COMMENT '总字节数',
`byteps_peak` UInt64 COMMENT '峰值带宽，单位为字节',
`downstream_bytes`UInt64 COMMENT '下行流量总字节数，单位为字节',
`upstream_bytes` UInt64 COMMENT '上行流量总字节数，单位为字节',
`total_payload_bytes` UInt64 COMMENT '总负载字节数',
`downstream_payload_bytes` UInt64 COMMENT '下行负载字节数',
`upstream_payload_bytes` UInt64 COMMENT '上行负载字节数',
`total_packets` UInt64 COMMENT '总包数',
`downstream_packets` UInt64 COMMENT '下行包数',
`upstream_packets` UInt64 COMMENT '上行包数',
`total_payload_packets` UInt64 COMMENT '总负载包数',
`downstream_payload_packets` UInt64 COMMENT '下行负载包数',
`upstream_payload_packets` UInt64 COMMENT '上行负载包数',
`tcp_syn_packets` UInt64 COMMENT 'TCP协议SYN包数',
`tcp_syn_ack_packets` UInt64 COMMENT 'TCP协议SYNACK包数',
`tcp_syn_rst_packets` UInt64 COMMENT 'TCP协议RST包数',
`established_sessions` UInt64 COMMENT '新建会话数',
`tcp_client_network_latency` UInt64 COMMENT 'TCP客户端网络总时延(ms)',
`tcp_client_network_latency_counts` UInt64 COMMENT 'TCP客户端网络时延次数',
`tcp_server_network_latency` UInt64 COMMENT 'TCP服务端网络总时延(ms)',
`tcp_server_network_latency_counts` UInt64 COMMENT 'TCP服务端网络时延次数',
`server_response_latency` UInt64 COMMENT '服务器响应总时延(ms)',
`server_response_latency_counts` UInt64 COMMENT '服务器响应时延总次数',
`tcp_client_retransmission_packets` UInt64 COMMENT 'TCP客户端重传包数',
`tcp_client_packets` UInt64 COMMENT 'TCP客户端包数',
`tcp_server_retransmission_packets` UInt64 COMMENT 'TCP服务端重传包数',
`tcp_server_packets` UInt64 COMMENT 'TCP服务端包数',
`tcp_zero_window_packets` UInt64 COMMENT 'TCP会话零窗口包数',
`tcp_client_zero_window_packets` UInt64 COMMENT 'TCP客户端零窗口包数',
`tcp_server_zero_window_packets` UInt64 COMMENT 'TCP服务端零窗口包数',
`tcp_established_fail_counts` UInt64 COMMENT 'TCP会话建连失败次数',
`tcp_established_success_counts` UInt64 COMMENT 'TCP会话建连成功次数',
INDEX i_network_id (network_id) TYPE bloom_filter() GRANULARITY 4,
INDEX i_service_id (service_id) TYPE bloom_filter() GRANULARITY 4,
INDEX i_application_id (application_id) TYPE minmax GRANULARITY 4,
INDEX i_category_id (category_id) TYPE minmax GRANULARITY 4,
INDEX i_subcategory_id (subcategory_id) TYPE minmax GRANULARITY 4,
INDEX i_type (type) TYPE minmax GRANULARITY 4,
INDEX i_total_bytes (total_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_byteps_peak (byteps_peak) TYPE minmax GRANULARITY 4, 
INDEX i_downstream_bytes (downstream_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_upstream_bytes (upstream_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_total_payload_bytes (total_payload_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_downstream_payload_bytes (downstream_payload_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_upstream_payload_bytes (upstream_payload_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_total_packets (total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_downstream_packets (downstream_packets) TYPE minmax GRANULARITY 4, 
INDEX i_upstream_packets (upstream_packets) TYPE minmax GRANULARITY 4, 
INDEX i_total_payload_packets (total_payload_packets) TYPE minmax GRANULARITY 4, 
INDEX i_downstream_payload_packets (downstream_payload_packets) TYPE minmax GRANULARITY 4, 
INDEX i_upstream_payload_packets (upstream_payload_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_syn_packets (tcp_syn_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_syn_ack_packets (tcp_syn_ack_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_syn_rst_packets (tcp_syn_rst_packets) TYPE minmax GRANULARITY 4, 
INDEX i_established_sessions (established_sessions) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_client_network_latency (tcp_client_network_latency) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_client_network_latency_counts (tcp_client_network_latency_counts) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_network_latency (tcp_server_network_latency) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_network_latency_counts (tcp_server_network_latency_counts) TYPE minmax GRANULARITY 4, 
INDEX i_server_response_latency (server_response_latency) TYPE minmax GRANULARITY 4, 
INDEX i_server_response_latency_counts (server_response_latency_counts) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_client_retransmission_packets (tcp_client_retransmission_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_client_packets (tcp_client_packets) TYPE minmax GRANULARITY 4,  
INDEX i_tcp_server_retransmission_packets (tcp_server_retransmission_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_packets (tcp_server_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_zero_window_packets (tcp_zero_window_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_client_zero_window_packets (tcp_client_zero_window_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_zero_window_packets (tcp_server_zero_window_packets) TYPE minmax GRANULARITY 4,  
INDEX i_tcp_established_fail_counts (tcp_established_fail_counts)  TYPE minmax GRANULARITY 4,
INDEX i_tcp_established_success_counts (tcp_established_success_counts)  TYPE minmax GRANULARITY 4
) 
ENGINE = MergeTree() 
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp)  
SETTINGS storage_policy = 'policy_hot_cold_0'
COMMENT '应用统计表'