CREATE TABLE IF NOT EXISTS fpc.t_fpc_metric_l3device_data_record
(
    `timestamp`                                              DateTime64(3, 'UTC') COMMENT '时间',
    `network_id`                                             String COMMENT '网络ID',
    `service_id`                                             String COMMENT '业务ID',
    `mac_address`                                            String COMMENT 'MAC地址',
    `ip_address`                                             String COMMENT 'IP地址',
    `ip_locality`                                            UInt8 COMMENT 'IP所在位置(0:内网,1:外网)',
    `total_bytes`                                            UInt64 COMMENT '总字节数',
    `downstream_bytes`                                       UInt64 COMMENT '下行流量字节数',
    `upstream_bytes`                                         UInt64 COMMENT '上行流量字节数',
    `total_packets`                                          UInt64 COMMENT '总包数',
    `downstream_packets`                                     UInt64 COMMENT '下行流量包数',
    `upstream_packets`                                       UInt64 COMMENT '上行流量包数',
    `tcp_syn_packets`                                        UInt64 COMMENT 'TCP协议SYN包数',
    `tcp_syn_ack_packets`                                    UInt64 COMMENT 'TCP协议SYNACK包数',
    `tcp_syn_rst_packets`                                    UInt64 COMMENT 'TCP协议RST包数',
    `established_sessions`                                   UInt64 COMMENT '新建会话数',
    `active_established_sessions`                            UInt64 COMMENT '主动新建会话数',
    `passive_established_sessions`                           UInt64 COMMENT '被动新建会话数',
    `tcp_client_network_latency`                             UInt64 COMMENT 'TCP客户端网络总时延(ms)',
    `tcp_client_network_latency_counts`                      UInt64 COMMENT 'TCP客户端网络时延次数',
    `tcp_server_network_latency`                             UInt64 COMMENT 'TCP服务端网络总时延(ms)',
    `tcp_server_network_latency_counts`                      UInt64 COMMENT 'TCP服务端网络时延次数',
    `server_response_latency`                                UInt64 COMMENT '服务器响应总时延(ms)',
    `server_response_latency_counts`                         UInt64 COMMENT '服务器响应时延总次数',
    `tcp_client_retransmission_packets`                      UInt64 COMMENT 'TCP客户端重传包数',
    `tcp_client_packets`                                     UInt64 COMMENT 'TCP客户端包数',
    `tcp_server_retransmission_packets`                      UInt64 COMMENT 'TCP服务端重传包数',
    `tcp_server_packets`                                     UInt64 COMMENT 'TCP服务端包数',
    `tcp_zero_window_packets`                                UInt64 COMMENT 'TCP零窗口包数',
    `tcp_client_zero_window_packets`                         UInt64 COMMENT 'TCP客户端零窗口包数',
    `tcp_server_zero_window_packets`                         UInt64 COMMENT 'TCP服务端零窗口包数',
    `tcp_established_fail_counts`                            UInt64 COMMENT 'TCP会话建连失败次数',
    `tcp_established_success_counts`                         UInt64 COMMENT 'TCP会话建连成功次数',
    `tcp_client_established_fail_counts_inside_service`      UInt64 COMMENT '内部服务-客户端-建连失败次数',
    `tcp_client_established_fail_counts_outside_service`     UInt64 COMMENT '外部服务-客户端-建连失败次数',
    `tcp_client_established_fail_counts`                     UInt64 COMMENT '全部服务-客户端-建连失败次数',
    `tcp_server_established_fail_counts_inside_service`      UInt64 COMMENT '内部服务-服务端-建连失败次数',
    `tcp_server_established_fail_counts_outside_service`     UInt64 COMMENT '外部服务-服务端-建连失败次数',
    `tcp_server_established_fail_counts`                     UInt64 COMMENT '全部服务-服务端-建连失败次数',
    `tcp_client_established_counts_inside_service`           UInt64 COMMENT '内部服务-客户端-建连总次数',
    `tcp_client_established_counts_outside_service`          UInt64 COMMENT '外部服务-客户端-建连总次数',
    `tcp_client_established_counts`                          UInt64 COMMENT '全部服务-客户端-建连总次数',
    `tcp_server_established_counts_inside_service`           UInt64 COMMENT '内部服务-服务端-建连总次数',
    `tcp_server_established_counts_outside_service`          UInt64 COMMENT '外部服务-服务端-建连总次数',
    `tcp_server_established_counts`                          UInt64 COMMENT '全部服务-服务端-建连总次数',
    `tcp_client_send_retransmission_packets_inside_service`  UInt64 COMMENT '内部服务-客户端-发送重传包数',
    `tcp_client_send_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-客户端-发送重传包数',
    `tcp_client_send_retransmission_packets`                 UInt64 COMMENT '全部服务-客户端-发送重传包数',
    `tcp_server_send_retransmission_packets_inside_service`  UInt64 COMMENT '内部服务-服务端-发送重传包数',
    `tcp_server_send_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-服务端-发送重传包数',
    `tcp_server_send_retransmission_packets`                 UInt64 COMMENT '全部服务-服务端-发送重传包数',
    `tcp_client_recv_retransmission_packets_inside_service`  UInt64 COMMENT '内部服务-客户端-接收重传包数',
    `tcp_client_recv_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-客户端-接收重传包数',
    `tcp_client_recv_retransmission_packets`                 UInt64 COMMENT '全部服务-客户端-接收重传包数',
    `tcp_server_recv_retransmission_packets_inside_service`  UInt64 COMMENT '内部服务-服务端-接收重传包数',
    `tcp_server_recv_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-服务端-接收重传包数',
    `tcp_server_recv_retransmission_packets`                 UInt64 COMMENT '全部服务-服务端-接收重传包数',
    `tcp_client_recv_packets_inside_service`                 UInt64 COMMENT '内部服务-客户端-接收总包数',
    `tcp_client_recv_packets_outside_service`                UInt64 COMMENT '外部服务-客户端-接收总包数',
    `tcp_client_recv_packets`                                UInt64 COMMENT '全部服务-客户端-接收总包数',
    `tcp_server_recv_packets_inside_service`                 UInt64 COMMENT '内部服务-服务端-接收总包数',
    `tcp_server_recv_packets_outside_service`                UInt64 COMMENT '外部服务-服务端-接收总包数',
    `tcp_server_recv_packets`                                UInt64 COMMENT '全部服务-服务端-接收总包数',
    `tcp_client_send_packets_inside_service`                 UInt64 COMMENT '内部服务-客户端-发送总包数',
    `tcp_client_send_packets_outside_service`                UInt64 COMMENT '外部服务-客户端-发送总包数',
    `tcp_client_send_packets`                                UInt64 COMMENT '全部服务-客户端-发送总包数',
    `tcp_server_send_packets_inside_service`                 UInt64 COMMENT '内部服务-服务端-发送总包数',
    `tcp_server_send_packets_outside_service`                UInt64 COMMENT '外部服务-服务端-发送总包数',
    `tcp_server_send_packets`                                UInt64 COMMENT '全部服务-服务端-发送总包数',
    INDEX i_network_id (network_id) TYPE bloom_filter() GRANULARITY 4,
    INDEX i_service_id (service_id) TYPE bloom_filter() GRANULARITY 4,
    INDEX i_mac_address (mac_address) TYPE bloom_filter() GRANULARITY 4,
    INDEX i_ip_address (ip_address) TYPE bloom_filter() GRANULARITY 4,
    INDEX i_ip_locality (ip_locality) TYPE minmax GRANULARITY 4,
    INDEX i_total_bytes (total_bytes) TYPE minmax GRANULARITY 4,
    INDEX i_downstream_bytes (downstream_bytes) TYPE minmax GRANULARITY 4,
    INDEX i_upstream_bytes (upstream_bytes) TYPE minmax GRANULARITY 4,
    INDEX i_total_packets (total_packets) TYPE minmax GRANULARITY 4,
    INDEX i_downstream_packets (downstream_packets) TYPE minmax GRANULARITY 4,
    INDEX i_upstream_packets (upstream_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_syn_packets (tcp_syn_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_syn_ack_packets (tcp_syn_ack_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_syn_rst_packets (tcp_syn_rst_packets) TYPE minmax GRANULARITY 4,
    INDEX i_established_sessions (established_sessions) TYPE minmax GRANULARITY 4,
    INDEX i_active_established_sessions (active_established_sessions) TYPE minmax GRANULARITY 4,
    INDEX i_passive_established_sessions (passive_established_sessions) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_network_latency (tcp_client_network_latency) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_network_latency_counts (tcp_client_network_latency_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_network_latency (tcp_server_network_latency) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_network_latency_counts (tcp_server_network_latency_counts) TYPE minmax GRANULARITY 4,
    INDEX i_server_response_latency (server_response_latency) TYPE minmax GRANULARITY 4,
    INDEX i_server_response_latency_counts (server_response_latency_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_retransmission_packets (tcp_client_retransmission_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_packets (tcp_client_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_retransmission_packets (tcp_server_retransmission_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_packets (tcp_server_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_zero_window_packets (tcp_zero_window_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_zero_window_packets (tcp_client_zero_window_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_zero_window_packets (tcp_server_zero_window_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_established_fail_counts (tcp_established_fail_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_established_success_counts (tcp_established_success_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_established_fail_counts_inside_service (tcp_client_established_fail_counts_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_established_fail_counts_outside_service (tcp_client_established_fail_counts_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_established_fail_counts (tcp_client_established_fail_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_established_fail_counts_inside_service (tcp_server_established_fail_counts_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_established_fail_counts_outside_service (tcp_server_established_fail_counts_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_established_fail_counts (tcp_server_established_fail_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_established_counts_inside_service (tcp_client_established_counts_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_established_counts_outside_service (tcp_client_established_counts_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_established_counts (tcp_client_established_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_established_counts_inside_service (tcp_server_established_counts_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_established_counts_outside_service (tcp_server_established_counts_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_established_counts (tcp_server_established_counts) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_recv_retransmission_packets_inside_service (tcp_client_recv_retransmission_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_send_retransmission_packets_inside_service (tcp_client_send_retransmission_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_recv_retransmission_packets_outside_service (tcp_client_recv_retransmission_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_send_retransmission_packets_outside_service (tcp_client_send_retransmission_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_recv_retransmission_packets (tcp_client_recv_retransmission_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_send_retransmission_packets (tcp_client_send_retransmission_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_recv_retransmission_packets_inside_service (tcp_server_recv_retransmission_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_send_retransmission_packets_inside_service (tcp_server_send_retransmission_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_recv_retransmission_packets_outside_service (tcp_server_recv_retransmission_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_send_retransmission_packets_outside_service (tcp_server_send_retransmission_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_recv_retransmission_packets (tcp_server_recv_retransmission_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_send_retransmission_packets (tcp_server_send_retransmission_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_recv_packets_inside_service (tcp_client_recv_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_send_packets_inside_service (tcp_client_send_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_recv_packets_outside_service (tcp_client_recv_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_send_packets_outside_service (tcp_client_send_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_recv_packets (tcp_client_recv_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_client_send_packets (tcp_client_send_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_recv_packets_inside_service (tcp_server_recv_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_send_packets_inside_service (tcp_server_send_packets_inside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_recv_packets_outside_service (tcp_server_recv_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_send_packets_outside_service (tcp_server_send_packets_outside_service) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_recv_packets (tcp_server_recv_packets) TYPE minmax GRANULARITY 4,
    INDEX i_tcp_server_send_packets (tcp_server_send_packets) TYPE minmax GRANULARITY 4
)
    ENGINE = MergeTree()
        PARTITION BY toYYYYMMDD(timestamp)
        ORDER BY (timestamp)
        SETTINGS storage_policy = 'policy_hot_cold_0'
        COMMENT 'IP地址统计表'