CREATE TABLE IF NOT EXISTS t_fpc_metric_service_in_second
(
`timestamp` DateTime64(3, 'UTC'), 
`start_time` DateTime64(3, 'UTC'), 
`network_id` LowCardinality(String),
`service_id` LowCardinality(String),
`alert_counts` UInt32,
`total_bytes` UInt64,
`total_packets` UInt64,
`upstream_bytes` UInt64,
`downstream_bytes` UInt64,
`fragment_total_bytes` UInt64,
`fragment_total_packets` UInt64,
`tcp_packets` UInt64,
`tcp_retransmission_packets` UInt64,
`tcp_client_packets` UInt64,
`tcp_client_retransmission_packets` UInt64,
`tcp_server_packets` UInt64,
`tcp_server_retransmission_packets` UInt64,
`tcp_client_network_latency` UInt64,
`tcp_client_network_latency_counts` UInt32,
`tcp_server_network_latency` UInt64,
`tcp_server_network_latency_counts` UInt32,
INDEX i_start_time (start_time) TYPE minmax GRANULARITY 4, 
INDEX i_network_id (network_id) TYPE bloom_filter() GRANULARITY 4,
INDEX i_service_id (service_id) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_alert_counts (alert_counts) TYPE minmax GRANULARITY 4, 
INDEX i_total_bytes (total_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_total_packets (total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_upstream_bytes (upstream_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_downstream_bytes (downstream_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_fragment_total_bytes (fragment_total_bytes) TYPE minmax GRANULARITY 4,
INDEX i_fragment_total_packets (fragment_total_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_packets (tcp_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_retransmission_packets (tcp_retransmission_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_client_packets (tcp_client_packets) TYPE minmax GRANULARITY 4,  
INDEX i_tcp_client_retransmission_packets (tcp_client_retransmission_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_packets (tcp_server_packets) TYPE minmax GRANULARITY 4,  
INDEX i_tcp_server_retransmission_packets (tcp_server_retransmission_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_client_network_latency (tcp_client_network_latency) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_client_network_latency_counts (tcp_client_network_latency_counts) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_network_latency (tcp_server_network_latency) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_network_latency_counts (tcp_server_network_latency_counts) TYPE minmax GRANULARITY 4
) 
ENGINE = MergeTree() 
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp) 