DROP TABLE IF EXISTS fpc.d_fpc_metric_location_data_record;
CREATE TABLE IF NOT EXISTS fpc.d_fpc_metric_location_data_record
(
`timestamp` DateTime64(3, 'UTC') COMMENT '记录时间',
`network_id` String COMMENT '网络ID',
`service_id` String COMMENT '业务ID',
`country_id` UInt16 COMMENT '国家ID',
`province_id` Nullable(UInt16) COMMENT '省份ID',
`city_id` Nullable(UInt16) COMMENT '城市ID',
`total_bytes` UInt64 COMMENT '总字节数',
`byteps_peak` UInt64 COMMENT '峰值带宽(byte/s)',
`downstream_bytes`UInt64 COMMENT '下行流量总字节数',
`upstream_bytes` UInt64 COMMENT '上行流量总字节数',
`total_payload_bytes` UInt64 COMMENT '总负载字节数',
`downstream_payload_bytes` UInt64 COMMENT '下行负载字节数',
`upstream_payload_bytes` UInt64 COMMENT '上行负载字节数',
`total_packets` UInt64 COMMENT '总包数',
`downstream_packets` UInt64 COMMENT '下行流量总包数',
`upstream_packets` UInt64 COMMENT '上行流量总包数',
`total_payload_packets` UInt64 COMMENT '总负载包数',
`downstream_payload_packets` UInt64 COMMENT '下行负载包数',
`upstream_payload_packets` UInt64 COMMENT '上行负载包数',
`tcp_syn_packets` UInt64 COMMENT 'TCP协议SYN包数',
`tcp_syn_ack_packets` UInt64 COMMENT 'TCP协议SYNACK包数',
`tcp_syn_rst_packets` UInt64 COMMENT 'TCP协议RST包数',
`established_sessions` UInt64 COMMENT '新建会话数',
`tcp_client_network_latency` UInt64 COMMENT 'TCP客户端网络总时延(ms)',
`tcp_client_network_latency_counts` UInt64 COMMENT 'TCP客户端网络时延次数',
`tcp_server_network_latency` UInt64 COMMENT 'TCP服务端网络总时延(ms)',
`tcp_server_network_latency_counts` UInt64 COMMENT 'TCP服务端网络时延次数',
`server_response_latency` UInt64 COMMENT '服务器响应总时延(ms)',
`server_response_latency_counts` UInt64 COMMENT '服务器响应时延总次数',
`tcp_client_retransmission_packets` UInt64 COMMENT 'TCP客户端重传包数',
`tcp_client_packets` UInt64 COMMENT 'TCP客户端包数',
`tcp_server_retransmission_packets` UInt64 COMMENT 'TCP服务端重传包数',
`tcp_server_packets` UInt64 COMMENT 'TCP服务端包数',
`tcp_zero_window_packets` UInt64 COMMENT 'TCP会话零窗口包数',
`tcp_client_zero_window_packets` UInt64 COMMENT 'TCP客户端零窗口包数',
`tcp_server_zero_window_packets` UInt64 COMMENT 'TCP服务端零窗口包数',
`tcp_established_fail_counts` UInt64 COMMENT 'TCP会话建连失败次数',
`tcp_established_success_counts` UInt64 COMMENT 'TCP会话建连成功次数'
) 
ENGINE = Distributed(ch_stats_servers, fpc, t_fpc_metric_location_data_record)
COMMENT '地区统计表';