DROP TABLE IF EXISTS fpc.d_fpc_metric_l3device_data_record;
CREATE TABLE IF NOT EXISTS fpc.d_fpc_metric_l3device_data_record
(
`timestamp` DateTime64(3, 'UTC') COMMENT '时间',
`network_id` String COMMENT '网络ID',
`service_id` String COMMENT '业务ID',
`mac_address` String COMMENT 'MAC地址',
`ip_address` String COMMENT 'IP地址',
`ip_locality` UInt8 COMMENT 'IP所在位置(0:内网,1:外网)',
`total_bytes` UInt64 COMMENT '总字节数',
`downstream_bytes` UInt64 COMMENT '下行流量字节数',
`upstream_bytes` UInt64 COMMENT '上行流量字节数',
`total_packets` UInt64 COMMENT '总包数',
`downstream_packets` UInt64 COMMENT '下行流量包数',
`upstream_packets` UInt64 COMMENT '上行流量包数',
`tcp_syn_packets` UInt64 COMMENT 'TCP协议SYN包数',
`tcp_syn_ack_packets` UInt64 COMMENT 'TCP协议SYNACK包数',
`tcp_syn_rst_packets` UInt64 COMMENT 'TCP协议RST包数',
`established_sessions` UInt64 COMMENT '新建会话数',
`active_established_sessions` UInt64 COMMENT '主动新建会话数',
`passive_established_sessions` UInt64 COMMENT '被动新建会话数',
`tcp_client_network_latency` UInt64 COMMENT 'TCP客户端网络总时延(ms)',
`tcp_client_network_latency_counts` UInt64 COMMENT 'TCP客户端网络时延次数',
`tcp_server_network_latency` UInt64 COMMENT 'TCP服务端网络总时延(ms)',
`tcp_server_network_latency_counts` UInt64 COMMENT 'TCP服务端网络时延次数',
`server_response_latency` UInt64 COMMENT '服务器响应总时延(ms)',
`server_response_latency_counts` UInt64 COMMENT '服务器响应时延总次数',
`tcp_client_retransmission_packets` UInt64 COMMENT 'TCP客户端重传包数',
`tcp_client_packets` UInt64 COMMENT 'TCP客户端包数',
`tcp_server_retransmission_packets` UInt64 COMMENT 'TCP服务端重传包数',
`tcp_server_packets` UInt64 COMMENT 'TCP服务端包数',
`tcp_zero_window_packets` UInt64 COMMENT 'TCP零窗口包数',
`tcp_client_zero_window_packets` UInt64 COMMENT 'TCP客户端零窗口包数',
`tcp_server_zero_window_packets` UInt64 COMMENT 'TCP服务端零窗口包数',
`tcp_established_fail_counts` UInt64 COMMENT 'TCP会话建连失败次数',
`tcp_established_success_counts` UInt64 COMMENT 'TCP会话建连成功次数',
`tcp_client_established_fail_counts_inside_service` UInt64 COMMENT '内部服务-客户端-建连失败次数',
`tcp_client_established_fail_counts_outside_service` UInt64 COMMENT '外部服务-客户端-建连失败次数',
`tcp_client_established_fail_counts` UInt64 COMMENT '全部服务-客户端-建连失败次数',
`tcp_server_established_fail_counts_inside_service` UInt64 COMMENT '内部服务-服务端-建连失败次数',
`tcp_server_established_fail_counts_outside_service` UInt64 COMMENT '外部服务-服务端-建连失败次数',
`tcp_server_established_fail_counts` UInt64 COMMENT '全部服务-服务端-建连失败次数',
`tcp_client_established_counts_inside_service` UInt64 COMMENT '内部服务-客户端-建连总次数',
`tcp_client_established_counts_outside_service` UInt64 COMMENT '外部服务-客户端-建连总次数',
`tcp_client_established_counts` UInt64 COMMENT '全部服务-客户端-建连总次数',
`tcp_server_established_counts_inside_service` UInt64 COMMENT '内部服务-服务端-建连总次数',
`tcp_server_established_counts_outside_service` UInt64 COMMENT '外部服务-服务端-建连总次数',
`tcp_server_established_counts` UInt64 COMMENT '全部服务-服务端-建连总次数',
`tcp_client_send_retransmission_packets_inside_service` UInt64 COMMENT '内部服务-客户端-发送重传包数',
`tcp_client_send_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-客户端-发送重传包数',
`tcp_client_send_retransmission_packets` UInt64 COMMENT '全部服务-客户端-发送重传包数',
`tcp_server_send_retransmission_packets_inside_service` UInt64 COMMENT '内部服务-服务端-发送重传包数',
`tcp_server_send_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-服务端-发送重传包数',
`tcp_server_send_retransmission_packets` UInt64 COMMENT '全部服务-服务端-发送重传包数',
`tcp_client_recv_retransmission_packets_inside_service` UInt64 COMMENT '内部服务-客户端-接收重传包数',
`tcp_client_recv_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-客户端-接收重传包数',
`tcp_client_recv_retransmission_packets` UInt64 COMMENT '全部服务-客户端-接收重传包数',
`tcp_server_recv_retransmission_packets_inside_service` UInt64 COMMENT '内部服务-服务端-接收重传包数',
`tcp_server_recv_retransmission_packets_outside_service` UInt64 COMMENT '外部服务-服务端-接收重传包数',
`tcp_server_recv_retransmission_packets` UInt64 COMMENT '全部服务-服务端-接收重传包数',
`tcp_client_recv_packets_inside_service` UInt64 COMMENT '内部服务-客户端-接收总包数',
`tcp_client_recv_packets_outside_service` UInt64 COMMENT '外部服务-客户端-接收总包数',
`tcp_client_recv_packets` UInt64 COMMENT '全部服务-客户端-接收总包数',
`tcp_server_recv_packets_inside_service` UInt64 COMMENT '内部服务-服务端-接收总包数',
`tcp_server_recv_packets_outside_service` UInt64 COMMENT '外部服务-服务端-接收总包数',
`tcp_server_recv_packets` UInt64 COMMENT '全部服务-服务端-接收总包数',
`tcp_client_send_packets_inside_service` UInt64 COMMENT '内部服务-客户端-发送总包数',
`tcp_client_send_packets_outside_service` UInt64 COMMENT '外部服务-客户端-发送总包数',
`tcp_client_send_packets` UInt64 COMMENT '全部服务-客户端-发送总包数',
`tcp_server_send_packets_inside_service` UInt64 COMMENT '内部服务-服务端-发送总包数',
`tcp_server_send_packets_outside_service` UInt64 COMMENT '外部服务-服务端-发送总包数',
`tcp_server_send_packets` UInt64 COMMENT '全部服务-服务端-发送总包数'
) 
ENGINE = Distributed(ch_stats_servers, fpc, t_fpc_metric_l3device_data_record)
COMMENT 'IP地址统计表';