CREATE TABLE IF NOT EXISTS t_fpc_metric_network_in_second
(
`timestamp` DateTime64(3, 'UTC'), 
`start_time` DateTime64(3, 'UTC'), 
`network_id` LowCardinality(String),
`alert_counts` UInt32,
`total_bytes` UInt64,
`total_packets` UInt64,
`upstream_bytes` UInt64,
`downstream_bytes` UInt64,
`tiny_packets` UInt64,
`small_packets` UInt64,
`medium_packets` UInt64,
`big_packets` UInt64,
`large_packets` UInt64,
`huge_packets` UInt64,
`jumbo_packets` UInt64,
`packet_length_avg` UInt64,
`tcp_total_packets` UInt64,
`udp_total_packets` UInt64,
`icmp_total_packets` UInt64,
`icmp6_total_packets` UInt64,
`other_total_packets` UInt64,
`ipv4_frames` UInt64,
`ipv6_frames` UInt64,
`arp_frames` UInt64,
`ieee8021x_frames` UInt64,
`ipx_frames` UInt64,
`lacp_frames` UInt64,
`mpls_frames` UInt64,
`stp_frames` UInt64,
`other_frames` UInt64,
`unicast_bytes` UInt64,
`broadcast_bytes` UInt64,
`multicast_bytes` UInt64,
`fragment_total_bytes` UInt64,
`fragment_total_packets` UInt64,
`tcp_packets` UInt64,
`tcp_retransmission_packets` UInt64,
`tcp_client_packets` UInt64,
`tcp_client_retransmission_packets` UInt64,
`tcp_server_packets` UInt64,
`tcp_server_retransmission_packets` UInt64,
`tcp_client_network_latency` UInt64,
`tcp_client_network_latency_counts` UInt32,
`tcp_server_network_latency` UInt64,
`tcp_server_network_latency_counts` UInt32,
INDEX i_start_time (start_time) TYPE minmax GRANULARITY 4, 
INDEX i_network_id (network_id) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_alert_counts (alert_counts) TYPE minmax GRANULARITY 4, 
INDEX i_total_bytes (total_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_total_packets (total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_upstream_bytes (upstream_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_downstream_bytes (downstream_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_tiny_packets (tiny_packets) TYPE minmax GRANULARITY 4, 
INDEX i_small_packets (small_packets) TYPE minmax GRANULARITY 4, 
INDEX i_medium_packets (medium_packets) TYPE minmax GRANULARITY 4, 
INDEX i_big_packets (big_packets) TYPE minmax GRANULARITY 4, 
INDEX i_large_packets (large_packets) TYPE minmax GRANULARITY 4, 
INDEX i_huge_packets (huge_packets) TYPE minmax GRANULARITY 4, 
INDEX i_jumbo_packets (jumbo_packets) TYPE minmax GRANULARITY 4, 
INDEX i_packet_length_avg (packet_length_avg) TYPE minmax GRANULARITY 4,
INDEX i_tcp_total_packets (tcp_total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_udp_total_packets (udp_total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_icmp_total_packets (icmp_total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_icmp6_total_packets (icmp6_total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_other_total_packets (other_total_packets) TYPE minmax GRANULARITY 4, 
INDEX i_ipv4_frames (ipv4_frames) TYPE minmax GRANULARITY 4, 
INDEX i_ipv6_frames (ipv6_frames) TYPE minmax GRANULARITY 4, 
INDEX i_arp_frames (arp_frames) TYPE minmax GRANULARITY 4, 
INDEX i_ieee8021x_frames (ieee8021x_frames) TYPE minmax GRANULARITY 4, 
INDEX i_ipx_frames (ipx_frames) TYPE minmax GRANULARITY 4, 
INDEX i_lacp_frames (lacp_frames) TYPE minmax GRANULARITY 4, 
INDEX i_mpls_frames (mpls_frames) TYPE minmax GRANULARITY 4, 
INDEX i_stp_frames (stp_frames) TYPE minmax GRANULARITY 4, 
INDEX i_other_frames (other_frames) TYPE minmax GRANULARITY 4, 
INDEX i_unicast_bytes (unicast_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_broadcast_bytes (broadcast_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_multicast_bytes (multicast_bytes) TYPE minmax GRANULARITY 4, 
INDEX i_fragment_total_bytes (fragment_total_bytes) TYPE minmax GRANULARITY 4,
INDEX i_fragment_total_packets (fragment_total_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_packets (tcp_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_retransmission_packets (tcp_retransmission_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_client_packets (tcp_client_packets) TYPE minmax GRANULARITY 4,  
INDEX i_tcp_client_retransmission_packets (tcp_client_retransmission_packets) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_packets (tcp_server_packets) TYPE minmax GRANULARITY 4,  
INDEX i_tcp_server_retransmission_packets (tcp_server_retransmission_packets) TYPE minmax GRANULARITY 4,
INDEX i_tcp_client_network_latency (tcp_client_network_latency) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_client_network_latency_counts (tcp_client_network_latency_counts) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_network_latency (tcp_server_network_latency) TYPE minmax GRANULARITY 4, 
INDEX i_tcp_server_network_latency_counts (tcp_server_network_latency_counts) TYPE minmax GRANULARITY 4
) 
ENGINE = MergeTree() 
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp)