import { bytesToSize } from "@/utils/utils";

export const DimensionsCol = [
  {
    title: '总字节数',
    dataIndex: 'totalBytes',
    key: '总字节数',
    sortOrder: 'descend',
    sorter: true,
    ellipsis: true,
    align: 'center',
    render: (text: any) => {
      return bytesToSize(text);
    },
  },
  {
    title: '接收字节数',
    dataIndex: 'downstreamBytes',
    key: '接收字节数',
    sorter: true,
    ellipsis: true,
    align: 'center',
    render: (text: any) => {
      return bytesToSize(text);
    },
  },
  {
    title: '发送字节数',
    dataIndex: 'upstreamBytes',
    key: '发送字节数',
    sorter: true,
    ellipsis: true,
    align: 'center',
    render: (text: any) => {
      return bytesToSize(text);
    },
  },
  {
    title: '服务器网络平均时延',
    dataIndex: 'tcpServerNetworkLatencyAvg',
    key: '服务器网络平均时延',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '客户端网络平均时延',
    dataIndex: 'tcpClientNetworkLatencyAvg',
    key: '客户端网络平均时延',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '服务器响应平均时延',
    dataIndex: 'serverResponseLatencyAvg',
    key: '服务器响应平均时延',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '总数据包',
    dataIndex: 'totalPackets',
    key: '总数据包',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '接收数据包数',
    dataIndex: 'downstreamPackets',
    key: '接收数据包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '发送数据包数',
    dataIndex: 'upstreamPackets',
    key: '发送数据包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '新建会话数',
    dataIndex: 'establishedSessions',
    key: '新建会话数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '客户端零窗口包数',
    dataIndex: 'tcpClientZeroWindowPackets',
    key: '客户端零窗口包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '服务端零窗口包数',
    dataIndex: 'tcpServerZeroWindowPackets',
    key: '服务端零窗口包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP建连成功数',
    dataIndex: 'tcpEstablishedSuccessCounts',
    key: 'TCP建连成功数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP建连失败数',
    dataIndex: 'tcpEstablishedFailCounts',
    key: 'TCP建连失败数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP客户端重传包数',
    dataIndex: 'tcpClientRetransmissionPackets',
    key: 'TCP客户端重传包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP客户端总包数',
    dataIndex: 'tcpClientPackets',
    key: 'TCP客户端总包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP服务端重传包数',
    dataIndex: 'tcpServerRetransmissionPackets',
    key: 'TCP服务端重传包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: 'TCP服务端总包数',
    dataIndex: 'tcpServerPackets',
    key: 'TCP服务端总包数',
    sorter: true,
    ellipsis: true,
    align: 'center',
  },
  {
    title: '操作',
    dataIndex: 'operate',
    key: '操作',
    sorter: false,
    ellipsis: false,
    align: 'center',
  },
];
