CREATE TABLE IF NOT EXISTS fpc.t_fpc_analysis_suricata_alert_message
( 
`timestamp` DateTime64(3, 'UTC') COMMENT '记录时间',
`sid` UInt32 COMMENT '检测规则ID',
`msg` String COMMENT '规则描述',
`network_id` LowCardinality(String) COMMENT '网络ID',
`classtype_id` String COMMENT '规则分类ID',
`mitre_tactic_id` String COMMENT '战术分类ID',
`mitre_technique_id` String COMMENT '技术分类ID',
`cve` String COMMENT 'CVE',
`cnnvd` String COMMENT 'CNNVD',
`signature_severity` String COMMENT '严重级别',
`target` String COMMENT '受害者',
`src_ipv4` Nullable(IPv4) COMMENT '源IPv4',
`src_ipv6` Nullable(IPv6) COMMENT '源IPv6',
`src_port` UInt16 COMMENT '源端口',
`dest_ipv4` Nullable(IPv4) COMMENT '目的IPv4',
`dest_ipv6` Nullable(IPv6) COMMENT '目的IPv6',
`dest_port` UInt16 COMMENT '目的端口',
`protocol` LowCardinality(String) COMMENT '传输层协议',
`l7_protocol` String COMMENT '应用协议',
`flow_id` UInt64 COMMENT '流ID',
`domain` String COMMENT '域名',
`url` String COMMENT 'URL',
`country_id_initiator` Nullable(UInt16) COMMENT '源国家ID', 
`province_id_initiator` Nullable(UInt16) COMMENT '源省份ID', 
`city_id_initiator` Nullable(UInt16) COMMENT '源城市ID', 
`country_id_responder` Nullable(UInt16) COMMENT '目的国家ID', 
`province_id_responder` Nullable(UInt16) COMMENT '目的省份ID', 
`city_id_responder` Nullable(UInt16) COMMENT '目的城市ID', 
`source` LowCardinality(String) COMMENT '来源',
`tag` Array(String) COMMENT '标签',
`basic_tag` LowCardinality(String) COMMENT '基础标签',
INDEX i_sid (sid) TYPE minmax GRANULARITY 4,
INDEX i_network_id (network_id) TYPE bloom_filter() GRANULARITY 4,
INDEX i_classtype_id (classtype_id) TYPE bloom_filter() GRANULARITY 4,
INDEX i_cve (cve) TYPE bloom_filter() GRANULARITY 4,
INDEX i_cnnvd (cnnvd) TYPE bloom_filter() GRANULARITY 4,
INDEX i_src_ipv4 (src_ipv4) TYPE minmax GRANULARITY 4, 
INDEX i_src_ipv6 (src_ipv6) TYPE minmax GRANULARITY 4, 
INDEX i_src_port (src_port) TYPE minmax GRANULARITY 4, 
INDEX i_dest_ipv4 (dest_ipv4) TYPE minmax GRANULARITY 4, 
INDEX i_dest_ipv6 (dest_ipv6) TYPE minmax GRANULARITY 4, 
INDEX i_dest_port (dest_port) TYPE minmax GRANULARITY 4, 
INDEX i_protocol (protocol) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_l7_protocol (l7_protocol) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_flow_id (flow_id) TYPE minmax GRANULARITY 4, 
INDEX i_signature_severity(signature_severity) TYPE bloom_filter() GRANULARITY 4,
INDEX i_country_id_initiator (country_id_initiator) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_province_id_initiator (province_id_initiator) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_city_id_initiator (city_id_initiator) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_country_id_responder (country_id_responder) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_province_id_responder (province_id_responder) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_city_id_responder (city_id_responder) TYPE bloom_filter() GRANULARITY 4,
INDEX i_source (source) TYPE bloom_filter() GRANULARITY 4,
INDEX i_tag (tag) TYPE bloom_filter() GRANULARITY 4,
INDEX i_basic_tag (basic_tag) TYPE bloom_filter() GRANULARITY 4
)
ENGINE = MergeTree() 
PARTITION BY toYYYYMMDD(timestamp)
ORDER BY (timestamp, sid, network_id) 
SETTINGS storage_policy = 'policy_hot_cold_0'
COMMENT '安全分析-安全告警消息'