CREATE TABLE IF NOT EXISTS fpc.t_fpc_protocol_ssl_log_record
(
`level` LowCardinality(String) COMMENT '采集策略等级',
`policy_name` LowCardinality(String) COMMENT '采集策略名称',
`flow_id` UInt64 COMMENT '流ID',
`network_id` Array(LowCardinality(String)) COMMENT '网络ID', 
`service_id` Array(LowCardinality(String)) COMMENT '业务ID',
`application_id` UInt32 COMMENT '应用ID',
`start_time` DateTime64(9, 'UTC') COMMENT '开始时间',
`end_time` DateTime64(9, 'UTC') COMMENT '结束时间',
`src_ipv4` Nullable(IPv4) COMMENT '源IPv4',
`src_ipv6` Nullable(IPv6) COMMENT '源IPv6',
`src_port` UInt16 COMMENT '源端口',
`dest_ipv4` Nullable(IPv4) COMMENT '目的IPv4',
`dest_ipv6` Nullable(IPv6) COMMENT '目的IPv6',
`dest_port` UInt16 COMMENT '目的端口',
`server_name` String COMMENT '服务器名称',
`server_certs_sha1` Array(String) COMMENT '服务器证书SHA1值',
`ja3_client` String COMMENT 'JA3客户端指纹',
`ja3_server` String COMMENT 'JA3服务端指纹',
`version` LowCardinality(String) COMMENT 'SSL版本',
`cipher_suite` LowCardinality(String) COMMENT '加密套件',
`signature_algorithm` LowCardinality(String) COMMENT '签名算法',
`issuer` LowCardinality(String) COMMENT '证书签发人',
`issuer_urls` String COMMENT '颁发者证书链接',
`ocsp_urls` String COMMENT '证书状态服务器',
`common_name` String COMMENT '证书使用者',
`validity` String COMMENT '证书有效期',
`certs_len` UInt16 COMMENT '证书链长度',
`crl_urls` String COMMENT '证书吊销列表链接',
`is_reuse` UInt8 COMMENT '会话复用（0表示未复用，1标识复用）',
`auth_type` UInt8 COMMENT '认证方式(0:单项向认证,1:双向认证)',
`client_cipher_suite` Array(String) COMMENT '客户端支持的加密套件',
`client_extensions` Array(LowCardinality(String)) COMMENT '客户端使用的拓展类型',
`server_extensions` Array(String) COMMENT '服务器使用的拓展类型',
`client_cur_version` Nullable(String) COMMENT '客户端当前使用的SSL版本',
`client_max_version` Nullable(String) COMMENT '客户端支持的最高SSL版本',
`sec_proto` UInt8 COMMENT 'DTLS标识（0：false;1:true）',
INDEX i_policy_name (policy_name) TYPE bloom_filter() GRANULARITY 4, 
INDEX i_flow_id (flow_id) TYPE minmax GRANULARITY 4, 
INDEX i_network_id (network_id) TYPE bloom_filter() GRANULARITY 4,
INDEX i_service_id (service_id) TYPE bloom_filter() GRANULARITY 4,  
INDEX i_application_id (application_id) TYPE minmax GRANULARITY 4,
INDEX i_end_time (end_time) TYPE minmax GRANULARITY 4, 
INDEX i_src_ipv4 (src_ipv4) TYPE minmax GRANULARITY 4, 
INDEX i_src_ipv6 (src_ipv6) TYPE minmax GRANULARITY 4, 
INDEX i_src_port (src_port) TYPE minmax GRANULARITY 4, 
INDEX i_dest_ipv4 (dest_ipv4) TYPE minmax GRANULARITY 4, 
INDEX i_dest_ipv6 (dest_ipv6) TYPE minmax GRANULARITY 4, 
INDEX i_dest_port (dest_port) TYPE minmax GRANULARITY 4, 
INDEX i_server_name (server_name) TYPE bloom_filter() GRANULARITY 4,
INDEX i_server_certs_sha1 (server_certs_sha1) TYPE bloom_filter() GRANULARITY 4,
INDEX i_ja3_client (ja3_client) TYPE bloom_filter() GRANULARITY 4,
INDEX i_ja3_server (ja3_server) TYPE bloom_filter() GRANULARITY 4,
INDEX i_version (version) TYPE bloom_filter() GRANULARITY 4,
INDEX i_issuer (issuer) TYPE bloom_filter() GRANULARITY 4,
INDEX i_issuer_urls (issuer_urls) TYPE bloom_filter() GRANULARITY 4,
INDEX i_ocsp_urls (ocsp_urls) TYPE bloom_filter() GRANULARITY 4,
INDEX i_common_name (common_name) TYPE bloom_filter() GRANULARITY 4,
INDEX i_auth_type (auth_type) TYPE minmax GRANULARITY 4,
INDEX i_sec_proto (sec_proto) TYPE minmax GRANULARITY 4
) 
ENGINE = MergeTree() 
PARTITION BY toYYYYMMDD(start_time)
ORDER BY (start_time, flow_id) 
SETTINGS storage_policy = 'policy_hot_cold_0'
COMMENT '应用层协议详单-SSL协议详单表'